import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = path.join(ROOT, 'data');
export const FUNDS_JSON = path.join(DATA_DIR, 'funds.json');
export const DATA_JS = path.join(ROOT, 'dashboard', 'data.js');

/**
 * Write the dataset both as JSON (for tooling) and as data.js (for the
 * dashboard — a plain <script> global, so the dashboard works when opened
 * straight from the filesystem, where fetch() of local JSON is blocked).
 */
export function writeOutputs(dataset) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(FUNDS_JSON, JSON.stringify(dataset, null, 2));
  fs.writeFileSync(
    DATA_JS,
    '// Generated by scripts/scrape.mjs — do not edit by hand.\n' +
      'window.FUND_DATA = ' + JSON.stringify(dataset, null, 2) + ';\n'
  );
  console.log(`→ Wrote ${FUNDS_JSON} and ${DATA_JS} (${dataset.funds.length} funds)`);
}

export function readDataset() {
  return JSON.parse(fs.readFileSync(FUNDS_JSON, 'utf8'));
}

/** Pick the first present key (case-insensitive) from a record. */
export function pick(record, candidates) {
  const lower = Object.fromEntries(Object.keys(record).map((k) => [k.toLowerCase(), k]));
  for (const c of candidates) {
    const k = lower[c.toLowerCase()];
    if (k !== undefined && record[k] !== null && record[k] !== undefined && record[k] !== '') {
      return record[k];
    }
  }
  return null;
}

export const num = (v) => {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(String(v).replace(/[%,\s]/g, ''));
  return Number.isFinite(n) ? n : null;
};
